
NS_ACTIVITY ='http://jabber.org/protocol/activity' # XEP-0108
NS_ADDRESS ='http://jabber.org/protocol/address' # XEP-0033
NS_ADMIN ='http://jabber.org/protocol/admin' # XEP-0133
NS_ADMIN_ADD_USER =NS_ADMIN+'#add-user' # XEP-0133
NS_ADMIN_DELETE_USER =NS_ADMIN+'#delete-user' # XEP-0133
NS_ADMIN_DISABLE_USER =NS_ADMIN+'#disable-user' # XEP-0133
NS_ADMIN_REENABLE_USER =NS_ADMIN+'#reenable-user' # XEP-0133
NS_ADMIN_END_USER_SESSION =NS_ADMIN+'#end-user-session' # XEP-0133
NS_ADMIN_GET_USER_PASSWORD =NS_ADMIN+'#get-user-password' # XEP-0133
NS_ADMIN_CHANGE_USER_PASSWORD =NS_ADMIN+'#change-user-password' # XEP-0133
NS_ADMIN_GET_USER_ROSTER =NS_ADMIN+'#get-user-roster' # XEP-0133
NS_ADMIN_GET_USER_LASTLOGIN =NS_ADMIN+'#get-user-lastlogin' # XEP-0133
NS_ADMIN_USER_STATS =NS_ADMIN+'#user-stats' # XEP-0133
NS_ADMIN_EDIT_BLACKLIST =NS_ADMIN+'#edit-blacklist' # XEP-0133
NS_ADMIN_EDIT_WHITELIST =NS_ADMIN+'#edit-whitelist' # XEP-0133
NS_ADMIN_REGISTERED_USERS_NUM =NS_ADMIN+'#get-registered-users-num' # XEP-0133
NS_ADMIN_DISABLED_USERS_NUM =NS_ADMIN+'#get-disabled-users-num' # XEP-0133
NS_ADMIN_ONLINE_USERS_NUM =NS_ADMIN+'#get-online-users-num' # XEP-0133
NS_ADMIN_ACTIVE_USERS_NUM =NS_ADMIN+'#get-active-users-num' # XEP-0133
NS_ADMIN_IDLE_USERS_NUM =NS_ADMIN+'#get-idle-users-num' # XEP-0133
NS_ADMIN_REGISTERED_USERS_LIST =NS_ADMIN+'#get-registered-users-list' # XEP-0133
NS_ADMIN_DISABLED_USERS_LIST =NS_ADMIN+'#get-disabled-users-list' # XEP-0133
NS_ADMIN_ONLINE_USERS_LIST =NS_ADMIN+'#get-online-users-list' # XEP-0133
NS_ADMIN_ACTIVE_USERS_LIST =NS_ADMIN+'#get-active-users-list' # XEP-0133
NS_ADMIN_IDLE_USERS_LIST =NS_ADMIN+'#get-idle-users-list' # XEP-0133
NS_ADMIN_ANNOUNCE =NS_ADMIN+'#announce' # XEP-0133
NS_ADMIN_SET_MOTD =NS_ADMIN+'#set-motd' # XEP-0133
NS_ADMIN_EDIT_MOTD =NS_ADMIN+'#edit-motd' # XEP-0133
NS_ADMIN_DELETE_MOTD =NS_ADMIN+'#delete-motd' # XEP-0133
NS_ADMIN_SET_WELCOME =NS_ADMIN+'#set-welcome' # XEP-0133
NS_ADMIN_DELETE_WELCOME =NS_ADMIN+'#delete-welcome' # XEP-0133
NS_ADMIN_EDIT_ADMIN =NS_ADMIN+'#edit-admin' # XEP-0133
NS_ADMIN_RESTART =NS_ADMIN+'#restart' # XEP-0133
NS_ADMIN_SHUTDOWN =NS_ADMIN+'#shutdown' # XEP-0133
NS_AGENTS ='jabber:iq:agents' # XEP-0094 (historical)
NS_AMP ='http://jabber.org/protocol/amp' # XEP-0079
NS_AMP_ERRORS =NS_AMP+'#errors' # XEP-0079
NS_AUTH ='jabber:iq:auth' # XEP-0078
NS_AVATAR ='jabber:iq:avatar' # XEP-0008 (historical)
NS_BIND ='urn:ietf:params:xml:ns:xmpp-bind' # RFC 3920
NS_BROWSE ='jabber:iq:browse' # XEP-0011 (historical)
NS_BYTESTREAM ='http://jabber.org/protocol/bytestreams' # XEP-0065
NS_CAPS ='http://jabber.org/protocol/caps' # XEP-0115
NS_CHATSTATES ='http://jabber.org/protocol/chatstates' # XEP-0085
NS_CLIENT ='jabber:client' # RFC 3921
NS_COMMANDS ='http://jabber.org/protocol/commands' # XEP-0050
NS_COMPONENT_ACCEPT ='jabber:component:accept' # XEP-0114
NS_COMPONENT_1 ='http://jabberd.jabberstudio.org/ns/component/1.0' # Jabberd2
NS_COMPRESS ='http://jabber.org/protocol/compress' # XEP-0138
NS_DATA ='jabber:x:data' # XEP-0004
NS_DATA_LAYOUT ='http://jabber.org/protocol/xdata-layout' # XEP-0141
NS_DATA_VALIDATE ='http://jabber.org/protocol/xdata-validate' # XEP-0122
NS_DELAY ='jabber:x:delay' # XEP-0091 (deprecated)
NS_DIALBACK ='jabber:server:dialback' # RFC 3921
NS_DISCO ='http://jabber.org/protocol/disco' # XEP-0030
NS_DISCO_INFO =NS_DISCO+'#info' # XEP-0030
NS_DISCO_ITEMS =NS_DISCO+'#items' # XEP-0030
NS_ENCRYPTED ='jabber:x:encrypted' # XEP-0027
NS_EVENT ='jabber:x:event' # XEP-0022 (deprecated)
NS_FEATURE ='http://jabber.org/protocol/feature-neg' # XEP-0020
NS_FILE ='http://jabber.org/protocol/si/profile/file-transfer' # XEP-0096
NS_GATEWAY ='jabber:iq:gateway' # XEP-0100
NS_GEOLOC ='http://jabber.org/protocol/geoloc' # XEP-0080
NS_GROUPCHAT ='gc-1.0' # XEP-0045
NS_HTTP_BIND ='http://jabber.org/protocol/httpbind' # XEP-0124
NS_IBB ='http://jabber.org/protocol/ibb' # XEP-0047
NS_INVISIBLE ='presence-invisible' # Jabberd2
NS_IQ ='iq' # Jabberd2
NS_LAST ='jabber:iq:last' # XEP-0012
NS_MESSAGE ='message' # Jabberd2
NS_MOOD ='http://jabber.org/protocol/mood' # XEP-0107
NS_MUC ='http://jabber.org/protocol/muc' # XEP-0045
NS_MUC_ADMIN =NS_MUC+'#admin' # XEP-0045
NS_MUC_OWNER =NS_MUC+'#owner' # XEP-0045
NS_MUC_UNIQUE =NS_MUC+'#unique' # XEP-0045
NS_MUC_USER =NS_MUC+'#user' # XEP-0045
NS_MUC_REGISTER =NS_MUC+'#register' # XEP-0045
NS_MUC_REQUEST =NS_MUC+'#request' # XEP-0045
NS_MUC_ROOMCONFIG =NS_MUC+'#roomconfig' # XEP-0045
NS_MUC_ROOMINFO =NS_MUC+'#roominfo' # XEP-0045
NS_MUC_ROOMS =NS_MUC+'#rooms' # XEP-0045
NS_MUC_TRAFIC =NS_MUC+'#traffic' # XEP-0045
NS_NICK ='http://jabber.org/protocol/nick' # XEP-0172
NS_OFFLINE ='http://jabber.org/protocol/offline' # XEP-0013
NS_PHYSLOC ='http://jabber.org/protocol/physloc' # XEP-0112
NS_PRESENCE ='presence' # Jabberd2
NS_PRIVACY ='jabber:iq:privacy' # RFC 3921
NS_PRIVATE ='jabber:iq:private' # XEP-0049
NS_PUBSUB ='http://jabber.org/protocol/pubsub' # XEP-0060
NS_REGISTER ='jabber:iq:register' # XEP-0077
NS_RC ='http://jabber.org/protocol/rc' # XEP-0146
NS_ROSTER ='jabber:iq:roster' # RFC 3921
NS_ROSTERX ='http://jabber.org/protocol/rosterx' # XEP-0144
NS_RPC ='jabber:iq:rpc' # XEP-0009
NS_SASL ='urn:ietf:params:xml:ns:xmpp-sasl' # RFC 3920
NS_SEARCH ='jabber:iq:search' # XEP-0055
NS_SERVER ='jabber:server' # RFC 3921
NS_SESSION ='urn:ietf:params:xml:ns:xmpp-session' # RFC 3921
NS_SI ='http://jabber.org/protocol/si' # XEP-0096
NS_SI_PUB ='http://jabber.org/protocol/sipub' # XEP-0137
NS_SIGNED ='jabber:x:signed' # XEP-0027
NS_STANZAS ='urn:ietf:params:xml:ns:xmpp-stanzas' # RFC 3920
NS_STREAMS ='http://etherx.jabber.org/streams' # RFC 3920
NS_TIME ='jabber:iq:time' # XEP-0090 (deprecated)
NS_TLS ='urn:ietf:params:xml:ns:xmpp-tls' # RFC 3920
NS_VACATION ='http://jabber.org/protocol/vacation' # XEP-0109
NS_VCARD ='vcard-temp' # XEP-0054
NS_VCARD_UPDATE ='vcard-temp:x:update' # XEP-0153
NS_VERSION ='jabber:iq:version' # XEP-0092
NS_WAITINGLIST ='http://jabber.org/protocol/waitinglist' # XEP-0130
NS_XHTML_IM ='http://jabber.org/protocol/xhtml-im' # XEP-0071
NS_XMPP_STREAMS ='urn:ietf:params:xml:ns:xmpp-streams' # RFC 3920
